### ISSUE TITLE
Autocomplete obscuring input

### ISSUE THREAD

**Issue by kflak** [madskjeldgaard/sc-scratchpad.nvim#1]
Beeeautiful plugin! But for one issue: the autocompletion menu obscures the text, which makes it difficult to use... I don't know if this is due to nui or the size of the scratchpad window (which I was, unfortunately), unable to change...

**Comment by madskjeldgaard** [comment]
Oh shit I forgot to activate user settings.... Will do so asap

**Comment by madskjeldgaard** [comment]
user settings are now actually used by the plugin :)
